# Site settings
title:       Let the data sing 
author:      Bobak Kechavarzi 
description: ":rocket: Going places with data"
baseurl:     "" 
url:         "https://bdkech.github.io"

# Social Links
email:            bdkech@gmail.com
twitter_username: kechbd 
github_username:  bdkech 

# Build settings
markdown: kramdown
permalink: pretty
