# Site settings
title:       Let the data sing 
author:      Bobak Kechavarzi 
description: ":rocket: Going places with data"
baseurl:     "" 
url:         "http://kechavarzi.com" 

# Social Links
email:            bkechava@imail.iu.edu 
twitter_username: kechbd 
github_username:  bdkech 

# Build settings
markdown: kramdown
permalink: pretty
